### PR TITLE
Greek translation

### PR DESCRIPTION
**Pull request by getimiskon**
I decided to create a Greek translation for the program. I tried to create a translation through POEditor, but it seems weird to use, and for the size of the project doing the changes manually with a text editor isn't hard at all.

Some strings that contain the word "instance" have been untranslated in purpose because there is no translation for that context.

### CODE REVIEW

**Comment by ManeraKai** [comment]
There are some discussions on replacing POEditor.

The word server is a good replacement. I translate the word instance in Arabic but add after it between parenthesis the word server to help explain. i.e: This instance (server) is an official one .

**Comment by getimiskon** [comment]
> The word `server` is a good replacement. I translate the word `instance` in Arabic but add after it between parenthesis the word `server` to help explain. i.e: `This instance (server) is an official one`.

I have been thinking of that when I was translating the text. I will do the changes to the translation later today.

> There are some discussions on replacing POEditor.
I see... It seemed rather cumbersome to use at first. It's easy to mess up if you don't know the interface there. For example, it's easy to accidentally apply as a contributor to a language that you don't even understand, for some reason.

**Comment by ManeraKai** [comment]
In the turkish translation, the translator added quotes to the word `instance`.
Ex: `Check instance.` => `"Instance" kontrol et"`

**Review by Valdnet — APPROVED** [review]

**Comment by ManeraKai** [comment]
LGTM. Thanks @getimiskon!

**Pull request merged**
